[window]
padding.x = 5
padding.y = 5
dynamic_padding = true
opacity = 0.80
blur = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
